// js/config.js
export const CONFIG = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  PLAYER_SIZE: 20,
  PLAYER_THRUST: 0.05,
  PLAYER_TURN_SPEED: 0.05,
  FRICTION: 0.99,
  BULLET_SPEED: 5,
  BULLET_MAX: 5,
  
  // Asteroid Configuration
  ASTEROID_NUM_START: 4,
  ASTEROID_LARGE_RADIUS: 40,
  ASTEROID_MEDIUM_RADIUS: 20,
  ASTEROID_SMALL_RADIUS: 10,
  ASTEROID_BASE_SPEED: 0.8,
  ASTEROID_SPEED_VARIATION: 0.4,
  ASTEROID_VERTICES: 10,
  ASTEROID_JAG: 0.4,
  ASTEROID_ROTATION_SPEED: 0.04, // Increased for more visible rotation
  LEVEL_SPEED_INCREASE: 0.1,
  
  // UFO Configuration
  UFO_SPAWN_TIME: 1800, // 30 seconds
  UFO_SPAWN_CHANCE: 0.25, // 25% chance when timer expires
  UFO_MIN_SCORE: 1000, // Minimum score before UFOs appear
  UFO_SPEED: 1.2,
  UFO_BULLET_SPEED: 3,
  
  // Scoring
  ASTEROID_LARGE_POINTS: 20,
  ASTEROID_MEDIUM_POINTS: 50,
  ASTEROID_SMALL_POINTS: 100,
  UFO_LARGE_POINTS: 200,
  UFO_SMALL_POINTS: 1000,
  
  // Game Settings
  HIGHSCORE_LIST_MAX: 5,
  EXTRA_LIFE_SCORE: 10000,
  HYPERSPACE_COOLDOWN: 200,
  GLOW_EFFECT: true,
  GLOW_BLUR: 10,
  
  // Visual Effects
  SHOW_TIMER: true,
  SHOW_FPS: false,
  PARTICLE_COUNT: 8,
  SCREEN_SHAKE: true,
};